### ISSUE TITLE
App not measuring all connected devices during second measurement in synced state

### ISSUE THREAD

**Issue by RinsRutgers** [xsens/xsens_dot_example_android#4]
After the last update syncing is not needed once done correctly. One should be able to start measuring a second time immediately but this feature is not working as it should in this version of the app. 

The app does go into syncing mode while the sensors output synced status. And after this, the app starts collecting data of only one sensor, although 4 are connected.

**Comment by fancycww** [comment]
Fixed, please check this commit: https://github.com/xsens/xsens_dot_example_android/commit/c024ebdabfc20ece5cc3a5c48450f976f0211e05
